# Generated by Django 2.2.3 on 2019-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circus', '0002_auto_20190717_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='address',
            field=models.CharField(default='defaultval', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='seats',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
