# Generated by Django 2.2.3 on 2019-07-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circus', '0003_auto_20190717_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='address',
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
