# Generated by Django 2.2.3 on 2019-07-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circus', '0004_auto_20190717_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='seats',
            new_name='booked_seats',
        ),
        migrations.AddField(
            model_name='show',
            name='total_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
