# Generated by Django 2.2.3 on 2019-07-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circus', '0005_auto_20190717_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='booked_seats',
            new_name='left_seats',
        ),
    ]
