# Generated by Django 2.2.3 on 2019-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circus', '0006_auto_20190717_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='paymentTime',
            field=models.DateTimeField(),
        ),
    ]
